### ISSUE TITLE
ICRC-3: Transaction Log

### ISSUE THREAD

**Issue by benjizhai** [dfinity/ICRC#3]
https://github.com/dfinity/ICRC-1/tree/icrc-3/standards/ICRC-3

**Comment by ulan** [comment]
Would it make sense to link https://github.com/dfinity/ICRC-1/issues/136 here?

**Comment by simplexforce** [comment]
> https://github.com/dfinity/ICRC-1/tree/icrc-3/standards/ICRC-3

404,  https://github.com/dfinity/ICRC-1/blob/main/standards/ICRC-3/README.md
