### ISSUE TITLE
`type` is not a proper field name in Block Schema

### ISSUE THREAD

**Issue by zensh** [dfinity/ICRC#65]
`type` is not a proper field name, it is a keyword and conflicts in most programming languages.

![image](https://github.com/dfinity/ICRC/assets/863754/8892ce5f-6117-40c2-b4c7-11b6a7b591ab)

@dietersommer

**Comment by dietersommer** [comment]
Excellent point, this should be addressed in ICRC-3. Many thanks for raising this!

**Comment by zensh** [comment]
Seems that it was changed to `btype`.
